runtime: python311

env_variables:
  GEMINI_API_KEY: "your-api-key-here"
  SECRET_KEY: "your-secret-key-here"
  
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
